import turtle
turtle.setup(800, 800)
t=turtle.Pen()
t.speed(10)
t.fillcolor("black")
t.begin_fill()
t.penup()
t.goto(0, -200)
t.pendown()
t.circle(200,180)
t.end_fill()
t.fillcolor("white")
t.begin_fill()
t.penup()
t.goto(0, 200)
t.pendown()
t.circle(200,180)
t.end_fill()
t.begin_fill()
t.penup()
t.goto(0,0)
t.pendown()
t.circle(100,180)
t.end_fill()
t.fillcolor("black")
t.begin_fill()
t.penup()
t.goto(0,0)
t.pendown()
t.circle(100,180)
t.end_fill()
t.fillcolor("white")
t.begin_fill()
t.penup()
t.goto(0,-130)
t.pendown()
t.circle(30)
t.end_fill()
t.fillcolor("black")
t.begin_fill()
t.penup()
t.goto(0,70)
t.pendown()
t.circle(30)
t.end_fill()
t.hideturtle()
turtle.done()